### ISSUE TITLE
您好，貌似有一个bug

### ISSUE THREAD

**Issue by linshuxi** [liuqh16/CloseAirCombat#12]
您好，simulator.py中的168行是这样的：Catalog.add_jsbsim_props(self.jsbsim_exec.query_property_catalog(""))
但是，根据jsbsim官方文档，self.jsbsim_exec.query_property_catalog("")返回的是一个字符串，但是Catalog.add_jsbsim_props()函数的输入对象是一个列表。所以这会导致与期望的结果不一致。ps: self.jsbsim_exec.query_property_catalog("")这里的参数真的是空吗？

第二个问题是，simulator.py中的第165行，self.jsbsim_exec = jsbsim.FGFDMExec(os.path.join(get_root_dir(), 'data'))，在data这个文件夹下边目前是没有数据的。

不知道是不是理解对了。

**Comment by Jackory** [comment]
您好，第一个问题你可以通过断点调试代码或者print函数输出，我们测试没有问题；第二个问题，您没有安装我们的提示完成前置条件。建议您跑通代码之后再提出问题。

**Comment by linshuxi** [comment]
好的哈，谢谢您的回复哈。

**Comment by leilei-0428** [comment]
@linshuxi 您好，我遇见了与您一样的问题，请问您跑通代码了吗？非常感谢，期待您的回复！

**Comment by suchenjm** [comment]
请问运行python envs/JSBSim/test/test_baseline_use_env.py语句时，报如下错误：
JSBSim startup beginning ...

Could not open file: Path "E:/code/python_execise/CloseAirCombat-master/CloseAirCombat-master/envs/JSBSim/utils/../data/aircraft/f16/f16.xml"
  JSBSim failed to open the configuration file: Path "E:/code/python_execise/CloseAirCombat-master/CloseAirCombat-master/envs/JSBSim/utils/../data/aircraft/f16/f16.xml"
Traceback (most recent call last):
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\test\test_baseline_use_env.py", line 163, in <module>
    test_maneuver()
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\test\test_baseline_use_env.py", line 142, in test_maneuver
    env = SingleCombatEnv(config_name='1v1/NoWeapon/test/opposite')
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\envs\singlecombat_env.py", line 12, in __init__
    super().__init__(config_name)
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\envs\env_base.py", line 31, in __init__
    self.load()
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\envs\env_base.py", line 55, in load
    self.load_simulator()
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\envs\env_base.py", line 64, in load_simulator
    self._jsbsims[uid] = AircraftSimulator(
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\core\simulatior.py", line 132, in __init__
    self.reload()
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\core\simulatior.py", line 168, in reload
    Catalog.add_jsbsim_props(self.jsbsim_exec.query_property_catalog(""))
  File "E:\code\python_execise\CloseAirCombat-master\CloseAirCombat-master\envs\JSBSim\core\catalog.py", line 553, in add_jsbsim_props
    [name_jsbsim, access] = jsbsim_prop.split(" ")
ValueError: not enough values to unpack (expected 2, got 1)
