### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by uuup111** [liuqh16/CloseAirCombat#30]
你好，安装好环境后运行报错了，报错代码如下：
`Process Process-32:
Traceback (most recent call last):
  File "/data/renyating/conda/envs/jsbsim/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/renyating/conda/envs/jsbsim/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/env_wrappers.py", line 207, in worker
    envs = [env_fn_wrapper() for env_fn_wrapper in env_fn_wrappers.x]
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/env_wrappers.py", line 207, in <listcomp>
    envs = [env_fn_wrapper() for env_fn_wrapper in env_fn_wrappers.x]
  File "train/train_jsbsim.py", line 26, in init_env
    env = SingleControlEnv(all_args.scenario_name)
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/singlecontrol_env.py", line 10, in __init__
    super().__init__(config_name)
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/env_base.py", line 31, in __init__
    self.load()
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/env_base.py", line 55, in load
    self.load_simulator()
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/env_base.py", line 64, in load_simulator
    self._jsbsims[uid] = AircraftSimulator(
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/core/simulatior.py", line 132, in __init__
    self.reload()
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/core/simulatior.py", line 168, in reload
    Catalog.add_jsbsim_props(self.jsbsim_exec.query_property_catalog(""))
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/core/catalog.py", line 552, in add_jsbsim_props
    jsbsim_props_tmp=jsbsim_props.split("\n")
AttributeError: 'list' object has no attribute 'split'
`
代码是在linux上运行的，环境是按照readme安装的。

**Comment by uuup111** [comment]
我重新装了个环境，尝试改变jsbsim版本，都没解决问题，网上也没有找到相关解决办法。不知道是哪个环节出了问题，能麻烦作者帮忙看看嘛？

**Comment by uuup111** [comment]
你好我跑了一下测试的代码，也会报错，看来好像是我版本不对？`

(jsbsim) jupyter-renyating@740xd-2:~/jsbsim/CloseAirCombat$ python test_env.py
DEBUG:root:AircraftSimulator:A0100 is created!


     JSBSim Flight Dynamics Model v1.1.6 [GitHub build 320/commit b477f6312bee2fd3af4c4e5ba1a3e732ed2b99d4] Apr 30 2021 12:03:39
            [JSBSim-ML v2.0]

JSBSim startup beginning ...

Traceback (most recent call last):
  File "test_env.py", line 70, in <module>
    test_multi_env()
  File "test_env.py", line 42, in test_multi_env
    envs = ShareDummyVecEnv([lambda: MultipleCombatEnv('2v2/NoWeapon/HierarchySelfplay') for _ in range(parallel_num)])
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/env_wrappers.py", line 341, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/env_wrappers.py", line 341, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "test_env.py", line 42, in <lambda>
    envs = ShareDummyVecEnv([lambda: MultipleCombatEnv('2v2/NoWeapon/HierarchySelfplay') for _ in range(parallel_num)])
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/multiplecombat_env.py", line 12, in __init__
    super().__init__(config_name)
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/env_base.py", line 31, in __init__
    self.load()
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/env_base.py", line 55, in load
    self.load_simulator()
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/envs/env_base.py", line 64, in load_simulator
    self._jsbsims[uid] = AircraftSimulator(
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/core/simulatior.py", line 132, in __init__
    self.reload()
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/core/simulatior.py", line 168, in reload
    Catalog.add_jsbsim_props(self.jsbsim_exec.query_property_catalog(""))
  File "/home/jupyter-renyating/jsbsim/CloseAirCombat/envs/JSBSim/core/catalog.py", line 552, in add_jsbsim_props
    jsbsim_props_tmp=jsbsim_props.split("\n")
AttributeError: 'list' object has no attribute 'split'
DEBUG:root:AircraftSimulator:A0100 is deleted!

`

**Comment by uuup111** [comment]
jsbsim_props它就是一个list还是一个字符串呢？
