### ISSUE TITLE
在运行train_heading.sh时遇到的问题

### ISSUE THREAD

**Issue by luolai123** [liuqh16/CloseAirCombat#32]
JSBSim startup beginning ...

Could not open file: Path "/home/robot/CloseAirCombat-master/envs/JSBSim/utils/../data/aircraft/f16/f16.xml"
  JSBSim failed to open the configuration file: Path "/home/robot/CloseAirCombat-master/envs/JSBSim/utils/../data/aircraft/f16/f16.xml"
Attempt to divide by zero in method     FGColumnVector3::operator/(const double scalar),     object 0 , 0 , 0

  A proper axis type has NOT been selected. Check your aerodynamics definition.
Traceback (most recent call last):
  File "train/train_jsbsim.py", line 171, in <module>
    main(sys.argv[1:])
  File "train/train_jsbsim.py", line 137, in main
    envs = make_train_env(all_args)
  File "train/train_jsbsim.py", line 44, in make_train_env
    return SubprocVecEnv([get_env_fn(i) for i in range(all_args.n_rollout_threads)])
  File "/home/robot/CloseAirCombat-master/envs/env_wrappers.py", line 263, in __init__
    observation_space, action_space = self.remotes[0].recv().x
  File "/home/robot/anaconda3/envs/jsbsim/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/robot/anaconda3/envs/jsbsim/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/robot/anaconda3/envs/jsbsim/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by luolai123** [comment]
看报错是轴或者通讯之类的 不太理解 希望有人解决

**Comment by dengshijie544** [comment]
网不好就不要用wandb了

**Comment by lizi-Margin** [comment]
不是别的问题，就是单纯的找不到文件。应把jsbsim的githb仓库克隆下来，把里面的内容放到到env/jsbsim/data。
